# Dependencies
markdown:         redcarpet
highlighter:      pygments
gems: [jekyll-paginate]

exclude:
    - .editorconfig
    - .env
    - .firebaserc
    - firebase.json
    - .git
    - .gitignore
    - Gemfile
    - Gemfile.lock
    - Makefile
    - README.md
    - gulpfile.js
    - node_modules
    - package.json
    - deploy.sh
    - src
    - cmd
    - bin

# Permalinks
permalink: "/posts/:title/"

# Setup
title:            ciarand.me
tagline:          'another code blog'
description:      ''
url:              http://ciarand.me
baseurl:          '/'
paginate:         5

author:
  name:           'Ciaran Downey'
  github:         https://github.com/ciarand
