# Dependencies
markdown:         redcarpet
highlighter:      pygments
gems: [jekyll-paginate]

exclude:
    - .editorconfig
    - .env
    - .gitignore
    - Makefile
    - README.md
    - gulpfile.js
    - package.json
    - node_modules

# Permalinks
permalink:        "/posts/:title"

# Setup
title:            ciarand.me
tagline:          'another code blog'
description:      ''
url:              http://ciarand.me
baseurl:          '/'
paginate:         3

author:
  name:           'Ciaran Downey'
  github:            https://github.com/ciarand
