# Dependencies
markdown:         redcarpet
highlighter:      true

# Permalinks
permalink:        pretty

# Setup
title:            ciarand.me
tagline:          'another code blog'
description:      ''
url:              http://ciarand.me
baseurl:          '/'
paginate:         3

author:
  name:           'Ciaran Downey'
  url:            https://github.com/ciarand

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
